#!/usr/bin/env python3
"""Rewrite a campaign's model block for a host that is not Jean-Zay.

The campaign configs name each base model by its Jean-Zay path under `$DSDIR`,
which `modeling.model_source` uses directly because it is a directory. No other
machine has that path. On a host whose weights live in an ordinary Hugging Face
cache the same function takes a different route: with `HF_HUB_OFFLINE=1` it asks
`snapshot_download` for the repo at a pinned revision and resolves it locally.
So porting a campaign is exactly one edit -- the repo id and the real revision
in place of the shared-store path -- and this script makes that edit rather than
leaving a hand-maintained copy to drift from the original.

The revision is not cosmetic. `campaign._run_id` hashes the model key and the
model *revision*, so a host variant necessarily mints its own run ids. That is
the honest outcome: an adapter trained here against a differently-pinned
checkout is not the Jean-Zay run and should not be able to claim its identity.

    scripts/make_host_config.py configs/conditional_trace_rate.yaml \
        configs/upnquick/conditional_trace_rate.yaml \
        --keep qwen25_7b_base \
        --model qwen25_7b_base=Qwen/Qwen2.5-7B@d149729398750b98c0af14eb82c78cfe92750796
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def rewrite(raw: dict, models: dict[str, tuple[str, str]], keep: list[str]) -> dict:
    unknown = set(models) - set(raw["models"])
    if unknown:
        raise SystemExit(f"config declares no model named {sorted(unknown)}")
    missing = [key for key in keep if key not in models]
    if missing:
        raise SystemExit(f"kept models with no host mapping: {missing}")
    for key, (name, revision) in models.items():
        raw["models"][key] = {**raw["models"][key], "name": name, "revision": revision}
    if keep:
        raw["models"] = {key: raw["models"][key] for key in keep}
        for study in raw["studies"].values():
            study["models"] = [key for key in study["models"] if key in keep]
        empty = [name for name, study in raw["studies"].items() if not study["models"]]
        if empty:
            # A study left with no model would expand to nothing and the missing
            # arm would only surface much later, as an unexplained empty sweep.
            raise SystemExit(f"studies left with no model: {empty}")
    return raw


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument(
        "--model", action="append", default=[], metavar="KEY=REPO@REVISION",
        help="host mapping for one model key; repeatable",
    )
    parser.add_argument(
        "--keep", action="append", default=[], metavar="KEY",
        help="restrict the config to these model keys; repeatable",
    )
    args = parser.parse_args()
    models = {}
    for item in args.model:
        key, _, rest = item.partition("=")
        name, _, revision = rest.partition("@")
        if not (key and name and revision):
            raise SystemExit(f"--model wants KEY=REPO@REVISION, got {item!r}")
        models[key] = (name, revision)
    raw = yaml.safe_load(args.source.read_text())
    result = rewrite(raw, models, args.keep)
    args.target.parent.mkdir(parents=True, exist_ok=True)
    args.target.write_text(
        f"# Generated by scripts/make_host_config.py from {args.source}.\n"
        f"# Edit the source and regenerate; do not edit this file.\n"
        + yaml.safe_dump(result, sort_keys=False)
    )
    print(f"{args.target}: {len(result['models'])} models, {len(result['studies'])} studies")


if __name__ == "__main__":
    main()
