#!/usr/bin/env python3
"""Write the sweep arms for the scale-and-task grid.

Sixteen cells differing in three fields is exactly the kind of file that grows a
typo nobody notices until a run has been scored against the wrong model. The
grid is small enough to read here and mechanical enough to generate, so it is
generated.
"""

from __future__ import annotations

from pathlib import Path

import yaml

CONFIG = "configs/jean_zay/scale_and_tasks.yaml"
OUT = Path("configs/jean_zay/scaling_sweep.yaml")

SCALES = [
    ("0p5b", "qwen25_0p5b_base"),
    ("1p5b", "qwen25_1p5b_base"),
    ("3b", "qwen25_3b_base"),
    ("7b", "qwen25_7b_base"),
    ("14b", "qwen25_14b_base"),
    ("32b", "qwen25_32b_base"),
]
# Pointer chasing runs on three of the six sizes, not all: the question there is
# whether the effect exists on a different task at all, and the small, middle
# and large ends answer that with a third of the jobs.
POINTER_SCALES = [scale for scale in SCALES if scale[0] in {"1p5b", "7b", "32b"}]
HOPS = (2, 4, 8)

HEADER = """# The sweep that reads every cell of the scale and task grid.
#
# One apparatus over twenty-one cells: six sizes of Qwen2.5 on the recorded
# chain-of-thought corruption, three sizes crossed with three pointer-chasing
# difficulties, a corruption those cells cannot shortcut, an instruction-tuned
# base to check the claim against a model that can already do the task, and one
# uncorrupted pointer arm as the control. Every cell is
# scored on the same seven conditions, so "recovery" -- the fraction of a cell's
# own damage that a condition undoes -- and "overshoot" -- how far past its own
# base model it lands -- are comparable across cells whose raw scores are not.
#
# Generated by scripts/write_scaling_arms.py; edit that, not this.
"""


def build() -> dict:
    arms: dict[str, dict] = {}
    for tag, model in SCALES:
        arms[f"cot_{tag}"] = {
            "config": CONFIG,
            "dataset": "cot_math_permuted",
            "evaluator": "gsm8k",
            "model": model,
            "rank": 16,
            "study": "scale_ladder",
        }
    for hops in HOPS:
        for tag, model in POINTER_SCALES:
            arms[f"ptr_h{hops}_{tag}"] = {
                "config": CONFIG,
                "dataset": f"pointer_h{hops}",
                "evaluator": "gsm8k",
                # A walk of eight steps is eight written lines; 160 tokens holds
                # four comfortably and 200 holds eight.
                "max_new_tokens": 200 if hops == 8 else 160,
                "model": model,
                "rank": 16,
                "study": "pointer_ladder",
            }
    # The corruption the task cannot shortcut, on the same three sizes. Permuted
    # working leaves a right answer that is recoverable from the prompt alone;
    # a mismatched response does not, so this is the arm where damage is
    # guaranteed and "does compression recover it" is a well-posed question.
    for tag, model in POINTER_SCALES:
        arms[f"ptr_mm_{tag}"] = {
            "config": CONFIG,
            "dataset": "pointer_h4_mismatched",
            "evaluator": "gsm8k",
            "max_new_tokens": 160,
            "model": model,
            "rank": 16,
            "study": "pointer_mismatched",
        }
    # An instruction-tuned base, because "beats the base model" only means
    # something when the base model can already do the task. A 1.5B base scores
    # zero on pointer chasing, which makes any adapter look like an improvement.
    for dataset, suffix in (("pointer_h4", "h4"), ("pointer_h4_mismatched", "mm")):
        arms[f"ptr_{suffix}_7b_inst"] = {
            "config": CONFIG,
            "dataset": dataset,
            "evaluator": "gsm8k",
            "max_new_tokens": 160,
            "model": "qwen25_7b_instruct",
            "rank": 16,
            "study": "pointer_instruct",
        }
    arms["ptr_h4_clean_7b"] = {
        "config": CONFIG,
        "dataset": "pointer_h4_clean",
        "evaluator": "gsm8k",
        "max_new_tokens": 160,
        "model": "qwen25_7b_base",
        "rank": 16,
        "study": "pointer_clean",
    }
    return {
        "arms": arms,
        "conditions": [
            "base",
            "raw",
            "rank1_b1",
            "rank1_b16",
            "scale_head_0p5",
            "norm_matched_b1",
            "tail_b16",
        ],
        "evaluation_batch_size": 32,
        "max_new_tokens": 512,
        "seed": 11,
        "smoke_rows": 8,
        "test_rows": 500,
        "version": 1,
    }


def main() -> None:
    document = build()
    OUT.write_text(
        HEADER + yaml.safe_dump(document, sort_keys=True, default_flow_style=False)
    )
    print(f"{OUT}: {len(document['arms'])} arms")
    # The same grid at eight rows a cell, for checking that a cell runs at all
    # before any real GPU time is spent on it. It writes to its own report
    # directory, so a smoke can never be mistaken for a measurement.
    smoke = {**document, "smoke": True, "test_rows": 8}
    smoke_path = OUT.with_name(OUT.stem + "_smoke.yaml")
    smoke_path.write_text(
        "# Eight rows a cell. A path check, not a measurement.\n"
        "# Generated by scripts/write_scaling_arms.py; edit that, not this.\n"
        + yaml.safe_dump(smoke, sort_keys=True, default_flow_style=False)
    )
    print(f"{smoke_path}: smoke variant")


if __name__ == "__main__":
    main()
