#!/usr/bin/env python3
"""Write the clean-rationale arms that the scale ladder never trained.

The ladder trained only the corrupted adapter at 0.5B, 1.5B and 3B. The clean
one is the same run with the rationales left in place: the same models,
adapter, recipe, rows and GSM8K test set, taken from scale_and_tasks.yaml so
the two cannot drift. That file stays untouched because the scaling grid's lock
hashes it.
"""

from __future__ import annotations

from pathlib import Path

import yaml

SOURCE = Path("configs/jean_zay/scale_and_tasks.yaml")
CONFIG = Path("configs/jean_zay/scale_clean.yaml")
SWEEP = Path("configs/jean_zay/scale_clean_sweep.yaml")
SCALES = [("0p5b", "qwen25_0p5b_base"), ("1p5b", "qwen25_1p5b_base"), ("3b", "qwen25_3b_base")]


def main() -> None:
    source = yaml.safe_load(SOURCE.read_text())
    clean = {k: v for k, v in source["datasets"]["cot_math_permuted"].items()
             if k != "rationale_control"}
    config = {
        **{k: v for k, v in source.items() if k not in {"models", "datasets", "studies", "training"}},
        "models": {model: source["models"][model] for _, model in SCALES},
        "datasets": {"cot_math": clean},
        "training": {"cot_full_1ep": source["training"]["cot_full_1ep"]},
        "studies": {"scale_clean": {**source["studies"]["scale_ladder"],
                                    "datasets": ["cot_math"],
                                    "models": [model for _, model in SCALES]}},
    }
    CONFIG.write_text("# Generated by scripts/write_scale_clean.py; edit that, not this.\n"
                      + yaml.safe_dump(config, sort_keys=True))
    sweep = {
        "arms": {f"clean_{tag}": {"config": str(CONFIG), "dataset": "cot_math",
                                  "evaluator": "gsm8k", "model": model, "rank": 16,
                                  "study": "scale_clean"} for tag, model in SCALES},
        # Base is rescored so each clean score sits beside a base from its own run.
        "conditions": ["base", "raw"],
        "evaluation_batch_size": 32,
        "max_new_tokens": 512,
        "seed": 11,
        "smoke_rows": 8,
        "test_rows": 500,
        "version": 1,
    }
    SWEEP.write_text("# Generated by scripts/write_scale_clean.py; edit that, not this.\n"
                     + yaml.safe_dump(sweep, sort_keys=True))
    print(CONFIG, SWEEP)


if __name__ == "__main__":
    main()
